# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hours_worked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
