# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='goal',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
